services:
  github_webhook_git_pull:
    build: .
    container_name: github_webhook_git_pull
    volumes:
      - ./repositories:/app/repositories
      - ./git-pull.sh:/app/git-pull.sh
      - ./app.py:/app/app.py
    environment:
      FLASK_APP: app.py
    ports:
      - "5015:5000"
    restart: always
