services:
  github_webhook_git_pull:
    build: .
    container_name: github_webhook_git_pull
    volumes:
      - ./repositories:/app/repositories
      # - ./git_pull.sh:/app/git_pull.sh
      - ./app.py:/app/app.py
    environment:
      FLASK_APP: app.py
    ports:
      - "5010:5000"
    restart: always
